name: database
services:
  postgres:
    image: postgres:17-alpine
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: booking-system
      POSTGRES_USER: veinhorn
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: no

volumes:
  postgres_data: