spring:
  application:
    name: booking-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/booking-system"
    username: veinhorn
    password: root
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    enabled: true